[versions]
# Libraries
kotlin = "1.6.21"
groovy = "3.0.13"
junit = "5.8.2"
graphql-java = "18.3"
graphql-kickstart-spring-boot = "13.0.1"
commons-text = "1.10.0"
spring-boot = "2.7.5"
spock = "2.1-groovy-3.0"
dgs = "5.4.1"

[libraries]
# BOMs
boms-junit = { module = "org.junit:junit-bom", version.ref = "junit" }
boms-spring-boot = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
boms-dgs = { module = "com.netflix.graphql.dgs:graphql-dgs-platform-dependencies", version.ref = "dgs" }

# Libraries
groovy-all = { module = "org.codehaus.groovy:groovy-all", version.ref = "groovy" }
graphql-kickstart-spring-boot-starter = { module = "com.graphql-java-kickstart:graphql-spring-boot-starter", version.ref = "graphql-kickstart-spring-boot" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commons-text" }
spock-core = { module = "org.spockframework:spock-core", version.ref = "spock" }
spock-spring = { module = "org.spockframework:spock-spring", version.ref = "spock" }
graphql-java = { module = "com.graphql-java:graphql-java", version.ref = "graphql-java" }
tailrocks-maven-publish-conventions = { module = "com.tailrocks.gradle:maven-publish-conventions", version = "0.1.12" }
tailrocks-signing-conventions = { module = "com.tailrocks.gradle:signing-conventions", version = "0.1.3" }

[plugins]
test-logger = { id = "com.adarshr.test-logger", version = "3.2.0" }
tailrocks-spotless = { id = "com.tailrocks.spotless", version = "0.1.4" }
tailrocks-java = { id = "com.tailrocks.java", version = "0.1.4" }
tailrocks-idea = { id = "com.tailrocks.idea", version = "0.1.3" }
tailrocks-junit = { id = "com.tailrocks.junit", version = "0.1.5" }
tailrocks-versions = { id = "com.tailrocks.versions", version = "0.1.4" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-plugin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.0" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
